### ISSUE TITLE
add slider component

### ISSUE THREAD

**Issue by maracuja-juice** [LINKIWI/react-elemental#61]
In one of the images on your documentation page I see that you use a slider. But there is no slider component in this library. It would be great to have one included in the library.

This is the image that I'm talking about:
![documentation image with slider component](https://static.kevinlin.info/blog/react-elemental/orion.png)

**Comment by LINKIWI** [comment]
This library is intended to be pretty composable in that it provides you with some UI primitives but it is expected that the client application implement more complex components using the building blocks that are provided. The slider (and others) are deliberately excluded from this library for this reason.

The component in the screenshot is implemented here though if you're interested.

https://github.com/LINKIWI/orion-web/blob/8c18dce19a2199c4c53e1145881d362a05018cd5/src/app/react/components/ui/slider.js

**Comment by maracuja-juice** [comment]
Thanks for your quick reaction. Will definitely look into that slider component of yours.
