### ISSUE TITLE
SelectList Improvement

### ISSUE THREAD

**Issue by periabyte** [LINKIWI/react-elemental#62]
Hi! Thanks for this very good library!
here are some features that'll be nice to have in the `SelectList` component.

- Searchable SelectList
- SelectList Direction (render options upwards or downwards)

**Comment by LINKIWI** [comment]
> Searchable SelectList

While interesting, Elemental is generally designed to provide you with a lot of UI component building blocks with a lot of overridable/customizable controls and expects you to implement more complex components with these building blocks. Searchable SelectList something I believe should be implemented outside the library itself.

(When I first published this library, I debated whether SelectList should be included at all. It is the most complex component that ships with Elemental.)

> SelectList Direction (render options upwards or downwards)

I like this idea.
